name: Cargo dependency cache
description: >
  Cache cargo's downloaded dependencies.
runs:
  using: composite
  steps:
    - name: Restore cargo dependency cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-deps-${{ runner.os }}-
