name: Cargo dependency cache
description: >
  Cache cargo's downloaded dependencies.
runs:
  using: composite
  steps:
    - name: Restore cargo dependency cache
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-deps-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-deps-${{ runner.os }}-
