[package]
name = "wfc"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { workspace = true }
rand = { workspace = true }

[dev-dependencies]
criterion = { version = "0.8", features = ["html_reports"] }

[[bench]]
name = "wfc_simple_bench"
harness = false

[[bench]]
name = "wfc_beach_bench"
harness = false

[[bench]]
name = "wfc_creatures_bench"
harness = false