name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-format:
    uses: ./.github/workflows/check-format.yaml
  run-tests:
    uses: ./.github/workflows/run-tests.yaml
  build-release:
    uses: ./.github/workflows/build-release.yaml
