name: Run tests

on:
  workflow_call:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: ./.github/actions/setup-mise
      - name: Run all tests
        run: mise run test
